### ISSUE TITLE
Title on top of sponsorship page (slider) doubled

### ISSUE THREAD

**Issue by LouisaKwasigroch** [clirdlf/forum2018#6]
https://forum2018.diglib.org/sponsorship-opportunities/

Shows up once in gray (small) and then appropriately in white (large).

**Comment by waynegraham** [comment]
Can I get a screenshot? I'm not seeing this.

Also, consider making that header shorter; maybe "Sponsorship Opportunities" and in the content DigiPres and Forum.

**Comment by kimnkl** [comment]
![Uploading Screen Shot 2017-12-01 at 10.40.04 AM.png…]()

![screen shot 2017-12-01 at 10 39 57 am](https://user-images.githubusercontent.com/8385041/33490163-2c2b648c-d684-11e7-83c3-c7cd3fc31739.png)

**Comment by kimnkl** [comment]
I can look into adding the DLF logo to all of them, like we do at the Home page. Thoughts @LouisaKwasigroch and @waynegraham? (It just replicates the title text if not.)

**Comment by LouisaKwasigroch** [comment]
When I'm signed out I don't see the double, at least not on the sponsorship
page. Anyone else?

**Comment by kimnkl** [comment]
![screen shot 2017-12-01 at 11 28 11 am](https://user-images.githubusercontent.com/8385041/33492357-d604fd8c-d68a-11e7-91bb-f36f4c86bcc7.png)

**Comment by kimnkl** [comment]
And it's still there when I sign out and go on the Travel + hotel page

**Comment by LouisaKwasigroch** [comment]
Yikes!

**Comment by waynegraham** [comment]
This is just a cache issue. Should be fine now.
