### ISSUE TITLE
Site footer

### ISSUE THREAD

**Issue by bquon** [clirdlf/forum2018#8]
It'd be great to have a separately blocked/colored footer, a la the 2017 site!

**Comment by waynegraham** [comment]
I'm not sure I understand this request. The footer in the 2017 site is a dark (`##00171F`), but is one color. Inside of that are four columns that are more blocked. 

In the Conference Pro theme, the color is lighter (`#cbf1f1`), but has the nav centered. 

Are you wanting to change the color and/or replace the nav at the bottom with the larger menus like on the forum2017 site?

**Comment by bquon** [comment]
Oh it already looks much better than it did! The bottom few sections were all the light blue before and I wasn't sure how to fix that.
Just gonna mark this resolved until we have more content--I would like to see a menu like last year's eventually, but that's once we have more to put there!
